name: flutter_test_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3

  get: ^4.6.6
  palette_generator: ^0.3.3+5
  path: ^1.9.0


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  solid_lints: ^0.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash.png
    - assets/images/


